name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-img:
    uses: ./.github/workflows/build-might-deploy.yml
    with:
      deploy: false
    permissions:
      contents: read
      pages: read
      packages: write

